# Generated by Django 6.0.2 on 2026-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[("food", "Food"), ("drink", "Drink")],
                default="food",
                max_length=10,
            ),
        ),
    ]
